# Generated by Django 6.0.6 on 2026-07-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('perime', 'Périmé')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=256)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
