# Generated by Django 6.0.6 on 2026-07-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouse_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse'),
        ),
    ]
