# Generated by Django 6.0.6 on 2026-07-04 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_warehouse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse'),
        ),
    ]
