# Generated by Django 6.0.6 on 2026-07-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_product_warehouse_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
    ]
